[workspace]
members = [
  "week250-all-unique",
  "week260-swap-pairs",
  "week264-fromto",
  "week267-ordinal-suffix",
  "week270-passes",
  "week280-replace-zeros",
  "week281-max-subarray",
  "week282-sum-every-other",
  "week284-missing-bits",
  "week286"
]
